In [2]:
# Numpy exercises (COMP1046)
import numpy as np

In [3]:
# Exercise 1

A = np.array([[2,3], [5,6], [1,7]])
B = np.array([[4,1,5,0],[3,2,6,3]])
print(A)
print(B)

print(all(A[1,:]==B[:,2]) )

[[2 3]
 [5 6]
 [1 7]]
[[4 1 5 0]
 [3 2 6 3]]
True


In [4]:
# Exercise 2

C = np.concatenate( (B,B) )
C[:,1] = [4,3,2,1]
print(C)
print(B)

[[4 4 5 0]
 [3 3 6 3]
 [4 2 5 0]
 [3 1 6 3]]
[[4 1 5 0]
 [3 2 6 3]]


In [8]:
# Exercise 3

D = np.array( [[0,3,4,0], [-1,0,2,1], [3,1,-1,-2], [-1,1,1,0]] )
print(D)

print(f"Determinant of D is {np.linalg.det(D)}.")
print("Inverse of D is")
print(np.linalg.inv(D))
print(f"Rank of D is {np.linalg.matrix_rank(D)}.")


[[ 0  3  4  0]
 [-1  0  2  1]
 [ 3  1 -1 -2]
 [-1  1  1  0]]
Determinant of D is -4.0.
Inverse of D is
[[ 0.5  -0.5  -0.25 -1.25]
 [ 1.   -2.   -1.   -1.  ]
 [-0.5   1.5   0.75  0.75]
 [ 1.5  -2.5  -1.75 -2.75]]
Rank of D is 4.


In [14]:
# Exercise 4

def secondary_diagonal(M):
    sd = np.zeros( (1, min(M.shape)) )
    for i in range(sd.shape[1]):
      sd[0,i] = M[i, M.shape[1]-i-1]
    return sd

secondary_diagonal(D)
secondary_diagonal(B)
secondary_diagonal(B.transpose() ) # extra test

array([[3., 1.]])